module.exports = [
    GAME_START: 'GAME_START',
    GAME_END: 'GAME_END',
    ROUND_START: 'ROUND_START',
    ROUND_END: 'ROUND_END',
    MULLIGAN_START: 'MULLIGAN_START',
    MULLIGAN_END: 'MULLIGAN_END',
    ATTACK: 'ATTACK',
    ATTACK_COMPLETE: 'ATTACK_COMPLETE'

];
